sudo: false
dist: trusty
language: c

addons:
  apt:
    packages:
      - latex-xcolor
      - pgf
      - python-pygments
      - texlive-base
      - texlive-fonts-extra
      - texlive-fonts-recommended
      - texlive-lang-english
      - texlive-latex-base
      - texlive-latex-extra
      - texlive-latex-recommended
      - texlive-pictures

install:
  - make

script:
  - true
