sudo: false
dist: xenial
language: c

addons:
  apt:
    packages:
      - cmake
      - latex-xcolor
      - lmodern
      - pgf
      - python-pygments
      - texlive-base
      - texlive-fonts-extra
      - texlive-fonts-recommended
      - texlive-lang-english
      - texlive-latex-base
      - texlive-latex-extra
      - texlive-latex-recommended
      - texlive-pictures
      - texlive-xetex

env:
  global:
    - secure: "UwYJ9pDrx7Y3dlwVlRZAUgpuEgZ4EtBCYNVQMhuY5lLyz1zVd1rN0RaR/5ZG7tT8Dko2aAu1SWRmcO2K1d5axvRUlaVNzS6ZxkEsO6UbPP2psIYkLlW8cmk/2C+i2AVcACxihNmdL14KmppemsEJHpaoLiHYyg/nYQCMhzLj/UrNGNDOFklwBM0FWtNgGyC2KHFK8YA1gPLeLsExd0hRPOI5CN2TUaVv8Qot6PiRsdYOVdedRQ/pwGAmrbynMeODLSa/edDnBHFKVD1l2YEJznUB5z6nMR7NDboifaYswnxXX8PefoYFvLEc7Vp4c4HVtHN8+b82MiGPBEitMnrLy7tVmb3tlmN4mjqW04gfdZ0UYhDHe5zerDLl1SrLA0gFpT9vIQgiIM6tUZ3Qi9VSykFz7Cejx90PhEwbm4+kLS948xyA4keTsoFht+aM9f3TfWktLyvpTD1jRunbPqtV91xE+L63SG3SqjIxo796ARITfGQ8aoKZecM0pT3dUfA4W173wstFZZlx0Ek3ST/yAW92UDJL3JBQIgjiaxr+re5u1AMkN/u+mTLbJQf6nQFSapWak3S7xPYhXVVaY5JnvxBxIfstR/SNiUs60LRRz46jrbh39QObeMM0DOTdHeknX6SyOeg/5Lg+7BJ1xspi89Pb8MKozSdF6pJxazjCuHE="
    - secure: "IDwaZpw6Pv0QK5fAx2RAyoeC3QiCTaEy8SaHjQrO+KJcQ1HpemBozKkW+zr61v87pjFvNMPkrIpxrlD6HhEYee295LaMlAhEBcJtrjHjRK0kyxdqv504gpQkOReNPwQRmvTaXYs4s7ljpEIt1hlwLH8xbZC9ktLslAiVP9/m8caaMTIs2MJyTddhQezaGOJ7MgYGJhMzSPwDcBkLLqzFi48aJwxh3EM1kOSvBYHnNw7TwAwAIY+i9EruPF/4NCXqRGUADNo96emq7l8VxUppbF4+4VtIwI0sUVkB6SzhF8s9rnUasv2VjymqMATbOtM84IerREgwQyxmNK0IMsp+wNE0wOmjfcj4rv6JHFuUTXiEw4ucYRSF0tdE3VoVFhC7Q+2dwQ4w+OY0xAe+d9xXm3O9pdDXkfWoQlNoiuosk6WPT64PPt9hsOwj6PSNnnizY5vzIk6okfLb5Cq/vdcuvrDHpho8eaDYuW8iU6lIRNqyb/rd38qLKfwx36/UC2KfqYdAFqkfFU+j4xG61hRPryNQJsdDCC4Eei7ucON22Dx+JjiTMbUGV5K4+bTRZSLW8duR8t4okxhS7D4MhoayrHn5ptUrgfOm7YIrLWMJUNe7XbeVsl3TuNIdnGhSyEmEgFuOG91I6OWSrnw+h6Qqy861BpQ1uoPVPwi8W84bpL0="

before_install:
  - openssl aes-256-cbc -K $encrypted_c02d706fc55b_key -iv $encrypted_c02d706fc55b_iv -in .travis/id_rsa.enc -out .travis/id_rsa -d
  - chmod 600 .travis/id_rsa

install:
  - true

script:
  - cmake .
  - make

after_success:
  - eval "$(ssh-agent -s)"
  - ssh-add .travis/id_rsa
  - rsync -qt -e "ssh -o BatchMode=yes -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o LogLevel=quiet -p $DEPLOY_PORT -l travis" build/gbctr.pdf $DEPLOY_HOST:gb-docs/gbctr.pdf > /dev/null 2>&1
