name: ci
on:
  pull_request:
  push:
    branches:
    - master

jobs:
  build:
    name: Build PDF
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          lfs: true
      - name: Install Ubuntu packages
        run: >
          sudo apt install
          cmake
          lmodern
          python-pygments
          texlive-base
          texlive-fonts-extra
          texlive-fonts-recommended
          texlive-lang-english
          texlive-latex-base
          texlive-latex-extra
          texlive-latex-recommended
          texlive-pictures
          texlive-xetex
      - name: Run cmake
        run: cmake .
      - name: Run make
        run: make
      - name: Upload log
        uses: actions/upload-artifact@v1
        if: failure()
        with:
          name: log
          path: build/gbctr.log
      - name: Upload built PDF
        uses: actions/upload-artifact@v1
        with:
          name: pdf
          path: build/gbctr.pdf
